name:  route
description:  A client + server routing library for Dart
version: 0.4.5
author: "Dart Authors <misc@dartlang.org>"
homepage: https://github.com/dart-lang/route

dependencies:
  browser: any
  logging: any
  unittest: any # using 'matchers'

environment:
  sdk: ">=0.4.7+1.r21548"
